// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/ClientChannels.proto

package protobuf;

public final class ClientChannels {
  private ClientChannels() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChannelBaseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.clientchannels.ChannelBase)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 channelId = 1;</code>
     * @return Whether the channelId field is set.
     */
    boolean hasChannelId();
    /**
     * <code>required int32 channelId = 1;</code>
     * @return The channelId.
     */
    int getChannelId();

    /**
     * <code>required string channelName = 2;</code>
     * @return Whether the channelName field is set.
     */
    boolean hasChannelName();
    /**
     * <code>required string channelName = 2;</code>
     * @return The channelName.
     */
    java.lang.String getChannelName();
    /**
     * <code>required string channelName = 2;</code>
     * @return The bytes for channelName.
     */
    com.google.protobuf.ByteString
        getChannelNameBytes();

    /**
     * <code>repeated int32 memberId = 3;</code>
     * @return A list containing the memberId.
     */
    java.util.List<java.lang.Integer> getMemberIdList();
    /**
     * <code>repeated int32 memberId = 3;</code>
     * @return The count of memberId.
     */
    int getMemberIdCount();
    /**
     * <code>repeated int32 memberId = 3;</code>
     * @param index The index of the element to return.
     * @return The memberId at the given index.
     */
    int getMemberId(int index);

    /**
     * <code>required int32 maxMembers = 4;</code>
     * @return Whether the maxMembers field is set.
     */
    boolean hasMaxMembers();
    /**
     * <code>required int32 maxMembers = 4;</code>
     * @return The maxMembers.
     */
    int getMaxMembers();

    /**
     * <code>required .protobuf.clientchannels.ChannelBase.ChannelRestrictionType restrictionType = 5;</code>
     * @return Whether the restrictionType field is set.
     */
    boolean hasRestrictionType();
    /**
     * <code>required .protobuf.clientchannels.ChannelBase.ChannelRestrictionType restrictionType = 5;</code>
     * @return The restrictionType.
     */
    protobuf.ClientChannels.ChannelBase.ChannelRestrictionType getRestrictionType();
  }
  /**
   * Protobuf type {@code protobuf.clientchannels.ChannelBase}
   */
  public  static final class ChannelBase extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.clientchannels.ChannelBase)
      ChannelBaseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChannelBase.newBuilder() to construct.
    private ChannelBase(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChannelBase() {
      channelName_ = "";
      memberId_ = emptyIntList();
      restrictionType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ChannelBase();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChannelBase(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              channelId_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              channelName_ = bs;
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                memberId_ = newIntList();
                mutable_bitField0_ |= 0x00000004;
              }
              memberId_.addInt(input.readInt32());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) != 0) && input.getBytesUntilLimit() > 0) {
                memberId_ = newIntList();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                memberId_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              maxMembers_ = input.readInt32();
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              protobuf.ClientChannels.ChannelBase.ChannelRestrictionType value = protobuf.ClientChannels.ChannelBase.ChannelRestrictionType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                restrictionType_ = rawValue;
              }
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) != 0)) {
          memberId_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.ClientChannels.internal_static_protobuf_clientchannels_ChannelBase_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.ClientChannels.internal_static_protobuf_clientchannels_ChannelBase_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.ClientChannels.ChannelBase.class, protobuf.ClientChannels.ChannelBase.Builder.class);
    }

    /**
     * Protobuf enum {@code protobuf.clientchannels.ChannelBase.ChannelRestrictionType}
     */
    public enum ChannelRestrictionType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>PUBLIC = 0;</code>
       */
      PUBLIC(0),
      /**
       * <code>WHITELIST_ONLY = 1;</code>
       */
      WHITELIST_ONLY(1),
      /**
       * <code>INVITE_ONLY = 2;</code>
       */
      INVITE_ONLY(2),
      ;

      /**
       * <code>PUBLIC = 0;</code>
       */
      public static final int PUBLIC_VALUE = 0;
      /**
       * <code>WHITELIST_ONLY = 1;</code>
       */
      public static final int WHITELIST_ONLY_VALUE = 1;
      /**
       * <code>INVITE_ONLY = 2;</code>
       */
      public static final int INVITE_ONLY_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ChannelRestrictionType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static ChannelRestrictionType forNumber(int value) {
        switch (value) {
          case 0: return PUBLIC;
          case 1: return WHITELIST_ONLY;
          case 2: return INVITE_ONLY;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ChannelRestrictionType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ChannelRestrictionType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ChannelRestrictionType>() {
              public ChannelRestrictionType findValueByNumber(int number) {
                return ChannelRestrictionType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return protobuf.ClientChannels.ChannelBase.getDescriptor().getEnumTypes().get(0);
      }

      private static final ChannelRestrictionType[] VALUES = values();

      public static ChannelRestrictionType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ChannelRestrictionType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:protobuf.clientchannels.ChannelBase.ChannelRestrictionType)
    }

    private int bitField0_;
    public static final int CHANNELID_FIELD_NUMBER = 1;
    private int channelId_;
    /**
     * <code>required int32 channelId = 1;</code>
     * @return Whether the channelId field is set.
     */
    public boolean hasChannelId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 channelId = 1;</code>
     * @return The channelId.
     */
    public int getChannelId() {
      return channelId_;
    }

    public static final int CHANNELNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object channelName_;
    /**
     * <code>required string channelName = 2;</code>
     * @return Whether the channelName field is set.
     */
    public boolean hasChannelName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string channelName = 2;</code>
     * @return The channelName.
     */
    public java.lang.String getChannelName() {
      java.lang.Object ref = channelName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          channelName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string channelName = 2;</code>
     * @return The bytes for channelName.
     */
    public com.google.protobuf.ByteString
        getChannelNameBytes() {
      java.lang.Object ref = channelName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        channelName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MEMBERID_FIELD_NUMBER = 3;
    private com.google.protobuf.Internal.IntList memberId_;
    /**
     * <code>repeated int32 memberId = 3;</code>
     * @return A list containing the memberId.
     */
    public java.util.List<java.lang.Integer>
        getMemberIdList() {
      return memberId_;
    }
    /**
     * <code>repeated int32 memberId = 3;</code>
     * @return The count of memberId.
     */
    public int getMemberIdCount() {
      return memberId_.size();
    }
    /**
     * <code>repeated int32 memberId = 3;</code>
     * @param index The index of the element to return.
     * @return The memberId at the given index.
     */
    public int getMemberId(int index) {
      return memberId_.getInt(index);
    }

    public static final int MAXMEMBERS_FIELD_NUMBER = 4;
    private int maxMembers_;
    /**
     * <code>required int32 maxMembers = 4;</code>
     * @return Whether the maxMembers field is set.
     */
    public boolean hasMaxMembers() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required int32 maxMembers = 4;</code>
     * @return The maxMembers.
     */
    public int getMaxMembers() {
      return maxMembers_;
    }

    public static final int RESTRICTIONTYPE_FIELD_NUMBER = 5;
    private int restrictionType_;
    /**
     * <code>required .protobuf.clientchannels.ChannelBase.ChannelRestrictionType restrictionType = 5;</code>
     * @return Whether the restrictionType field is set.
     */
    public boolean hasRestrictionType() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required .protobuf.clientchannels.ChannelBase.ChannelRestrictionType restrictionType = 5;</code>
     * @return The restrictionType.
     */
    public protobuf.ClientChannels.ChannelBase.ChannelRestrictionType getRestrictionType() {
      @SuppressWarnings("deprecation")
      protobuf.ClientChannels.ChannelBase.ChannelRestrictionType result = protobuf.ClientChannels.ChannelBase.ChannelRestrictionType.valueOf(restrictionType_);
      return result == null ? protobuf.ClientChannels.ChannelBase.ChannelRestrictionType.PUBLIC : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasChannelId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasChannelName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMaxMembers()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRestrictionType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, channelId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, channelName_);
      }
      for (int i = 0; i < memberId_.size(); i++) {
        output.writeInt32(3, memberId_.getInt(i));
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(4, maxMembers_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeEnum(5, restrictionType_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, channelId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, channelName_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < memberId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(memberId_.getInt(i));
        }
        size += dataSize;
        size += 1 * getMemberIdList().size();
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, maxMembers_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, restrictionType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protobuf.ClientChannels.ChannelBase)) {
        return super.equals(obj);
      }
      protobuf.ClientChannels.ChannelBase other = (protobuf.ClientChannels.ChannelBase) obj;

      if (hasChannelId() != other.hasChannelId()) return false;
      if (hasChannelId()) {
        if (getChannelId()
            != other.getChannelId()) return false;
      }
      if (hasChannelName() != other.hasChannelName()) return false;
      if (hasChannelName()) {
        if (!getChannelName()
            .equals(other.getChannelName())) return false;
      }
      if (!getMemberIdList()
          .equals(other.getMemberIdList())) return false;
      if (hasMaxMembers() != other.hasMaxMembers()) return false;
      if (hasMaxMembers()) {
        if (getMaxMembers()
            != other.getMaxMembers()) return false;
      }
      if (hasRestrictionType() != other.hasRestrictionType()) return false;
      if (hasRestrictionType()) {
        if (restrictionType_ != other.restrictionType_) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasChannelId()) {
        hash = (37 * hash) + CHANNELID_FIELD_NUMBER;
        hash = (53 * hash) + getChannelId();
      }
      if (hasChannelName()) {
        hash = (37 * hash) + CHANNELNAME_FIELD_NUMBER;
        hash = (53 * hash) + getChannelName().hashCode();
      }
      if (getMemberIdCount() > 0) {
        hash = (37 * hash) + MEMBERID_FIELD_NUMBER;
        hash = (53 * hash) + getMemberIdList().hashCode();
      }
      if (hasMaxMembers()) {
        hash = (37 * hash) + MAXMEMBERS_FIELD_NUMBER;
        hash = (53 * hash) + getMaxMembers();
      }
      if (hasRestrictionType()) {
        hash = (37 * hash) + RESTRICTIONTYPE_FIELD_NUMBER;
        hash = (53 * hash) + restrictionType_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobuf.ClientChannels.ChannelBase parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.ClientChannels.ChannelBase parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.ClientChannels.ChannelBase parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.ClientChannels.ChannelBase parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.ClientChannels.ChannelBase parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.ClientChannels.ChannelBase parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.ClientChannels.ChannelBase parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.ClientChannels.ChannelBase parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.ClientChannels.ChannelBase parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protobuf.ClientChannels.ChannelBase parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.ClientChannels.ChannelBase parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.ClientChannels.ChannelBase parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.ClientChannels.ChannelBase prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.clientchannels.ChannelBase}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.clientchannels.ChannelBase)
        protobuf.ClientChannels.ChannelBaseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.ClientChannels.internal_static_protobuf_clientchannels_ChannelBase_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.ClientChannels.internal_static_protobuf_clientchannels_ChannelBase_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.ClientChannels.ChannelBase.class, protobuf.ClientChannels.ChannelBase.Builder.class);
      }

      // Construct using protobuf.ClientChannels.ChannelBase.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        channelId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        channelName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        memberId_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000004);
        maxMembers_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        restrictionType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.ClientChannels.internal_static_protobuf_clientchannels_ChannelBase_descriptor;
      }

      @java.lang.Override
      public protobuf.ClientChannels.ChannelBase getDefaultInstanceForType() {
        return protobuf.ClientChannels.ChannelBase.getDefaultInstance();
      }

      @java.lang.Override
      public protobuf.ClientChannels.ChannelBase build() {
        protobuf.ClientChannels.ChannelBase result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protobuf.ClientChannels.ChannelBase buildPartial() {
        protobuf.ClientChannels.ChannelBase result = new protobuf.ClientChannels.ChannelBase(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.channelId_ = channelId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.channelName_ = channelName_;
        if (((bitField0_ & 0x00000004) != 0)) {
          memberId_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.memberId_ = memberId_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.maxMembers_ = maxMembers_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.restrictionType_ = restrictionType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.ClientChannels.ChannelBase) {
          return mergeFrom((protobuf.ClientChannels.ChannelBase)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.ClientChannels.ChannelBase other) {
        if (other == protobuf.ClientChannels.ChannelBase.getDefaultInstance()) return this;
        if (other.hasChannelId()) {
          setChannelId(other.getChannelId());
        }
        if (other.hasChannelName()) {
          bitField0_ |= 0x00000002;
          channelName_ = other.channelName_;
          onChanged();
        }
        if (!other.memberId_.isEmpty()) {
          if (memberId_.isEmpty()) {
            memberId_ = other.memberId_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureMemberIdIsMutable();
            memberId_.addAll(other.memberId_);
          }
          onChanged();
        }
        if (other.hasMaxMembers()) {
          setMaxMembers(other.getMaxMembers());
        }
        if (other.hasRestrictionType()) {
          setRestrictionType(other.getRestrictionType());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasChannelId()) {
          return false;
        }
        if (!hasChannelName()) {
          return false;
        }
        if (!hasMaxMembers()) {
          return false;
        }
        if (!hasRestrictionType()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.ClientChannels.ChannelBase parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.ClientChannels.ChannelBase) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int channelId_ ;
      /**
       * <code>required int32 channelId = 1;</code>
       * @return Whether the channelId field is set.
       */
      public boolean hasChannelId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int32 channelId = 1;</code>
       * @return The channelId.
       */
      public int getChannelId() {
        return channelId_;
      }
      /**
       * <code>required int32 channelId = 1;</code>
       * @param value The channelId to set.
       * @return This builder for chaining.
       */
      public Builder setChannelId(int value) {
        bitField0_ |= 0x00000001;
        channelId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 channelId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearChannelId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        channelId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object channelName_ = "";
      /**
       * <code>required string channelName = 2;</code>
       * @return Whether the channelName field is set.
       */
      public boolean hasChannelName() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string channelName = 2;</code>
       * @return The channelName.
       */
      public java.lang.String getChannelName() {
        java.lang.Object ref = channelName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            channelName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string channelName = 2;</code>
       * @return The bytes for channelName.
       */
      public com.google.protobuf.ByteString
          getChannelNameBytes() {
        java.lang.Object ref = channelName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          channelName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string channelName = 2;</code>
       * @param value The channelName to set.
       * @return This builder for chaining.
       */
      public Builder setChannelName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        channelName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string channelName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearChannelName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        channelName_ = getDefaultInstance().getChannelName();
        onChanged();
        return this;
      }
      /**
       * <code>required string channelName = 2;</code>
       * @param value The bytes for channelName to set.
       * @return This builder for chaining.
       */
      public Builder setChannelNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        channelName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList memberId_ = emptyIntList();
      private void ensureMemberIdIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          memberId_ = mutableCopy(memberId_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated int32 memberId = 3;</code>
       * @return A list containing the memberId.
       */
      public java.util.List<java.lang.Integer>
          getMemberIdList() {
        return ((bitField0_ & 0x00000004) != 0) ?
                 java.util.Collections.unmodifiableList(memberId_) : memberId_;
      }
      /**
       * <code>repeated int32 memberId = 3;</code>
       * @return The count of memberId.
       */
      public int getMemberIdCount() {
        return memberId_.size();
      }
      /**
       * <code>repeated int32 memberId = 3;</code>
       * @param index The index of the element to return.
       * @return The memberId at the given index.
       */
      public int getMemberId(int index) {
        return memberId_.getInt(index);
      }
      /**
       * <code>repeated int32 memberId = 3;</code>
       * @param index The index to set the value at.
       * @param value The memberId to set.
       * @return This builder for chaining.
       */
      public Builder setMemberId(
          int index, int value) {
        ensureMemberIdIsMutable();
        memberId_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 memberId = 3;</code>
       * @param value The memberId to add.
       * @return This builder for chaining.
       */
      public Builder addMemberId(int value) {
        ensureMemberIdIsMutable();
        memberId_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 memberId = 3;</code>
       * @param values The memberId to add.
       * @return This builder for chaining.
       */
      public Builder addAllMemberId(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureMemberIdIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, memberId_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 memberId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMemberId() {
        memberId_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      private int maxMembers_ ;
      /**
       * <code>required int32 maxMembers = 4;</code>
       * @return Whether the maxMembers field is set.
       */
      public boolean hasMaxMembers() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required int32 maxMembers = 4;</code>
       * @return The maxMembers.
       */
      public int getMaxMembers() {
        return maxMembers_;
      }
      /**
       * <code>required int32 maxMembers = 4;</code>
       * @param value The maxMembers to set.
       * @return This builder for chaining.
       */
      public Builder setMaxMembers(int value) {
        bitField0_ |= 0x00000008;
        maxMembers_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 maxMembers = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxMembers() {
        bitField0_ = (bitField0_ & ~0x00000008);
        maxMembers_ = 0;
        onChanged();
        return this;
      }

      private int restrictionType_ = 0;
      /**
       * <code>required .protobuf.clientchannels.ChannelBase.ChannelRestrictionType restrictionType = 5;</code>
       * @return Whether the restrictionType field is set.
       */
      public boolean hasRestrictionType() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>required .protobuf.clientchannels.ChannelBase.ChannelRestrictionType restrictionType = 5;</code>
       * @return The restrictionType.
       */
      public protobuf.ClientChannels.ChannelBase.ChannelRestrictionType getRestrictionType() {
        @SuppressWarnings("deprecation")
        protobuf.ClientChannels.ChannelBase.ChannelRestrictionType result = protobuf.ClientChannels.ChannelBase.ChannelRestrictionType.valueOf(restrictionType_);
        return result == null ? protobuf.ClientChannels.ChannelBase.ChannelRestrictionType.PUBLIC : result;
      }
      /**
       * <code>required .protobuf.clientchannels.ChannelBase.ChannelRestrictionType restrictionType = 5;</code>
       * @param value The restrictionType to set.
       * @return This builder for chaining.
       */
      public Builder setRestrictionType(protobuf.ClientChannels.ChannelBase.ChannelRestrictionType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        restrictionType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .protobuf.clientchannels.ChannelBase.ChannelRestrictionType restrictionType = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearRestrictionType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        restrictionType_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.clientchannels.ChannelBase)
    }

    // @@protoc_insertion_point(class_scope:protobuf.clientchannels.ChannelBase)
    private static final protobuf.ClientChannels.ChannelBase DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protobuf.ClientChannels.ChannelBase();
    }

    public static protobuf.ClientChannels.ChannelBase getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ChannelBase>
        PARSER = new com.google.protobuf.AbstractParser<ChannelBase>() {
      @java.lang.Override
      public ChannelBase parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChannelBase(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChannelBase> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChannelBase> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protobuf.ClientChannels.ChannelBase getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TextChannelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.clientchannels.TextChannel)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .protobuf.clientchannels.ChannelBase channelBase = 1;</code>
     * @return Whether the channelBase field is set.
     */
    boolean hasChannelBase();
    /**
     * <code>required .protobuf.clientchannels.ChannelBase channelBase = 1;</code>
     * @return The channelBase.
     */
    protobuf.ClientChannels.ChannelBase getChannelBase();
    /**
     * <code>required .protobuf.clientchannels.ChannelBase channelBase = 1;</code>
     */
    protobuf.ClientChannels.ChannelBaseOrBuilder getChannelBaseOrBuilder();
  }
  /**
   * Protobuf type {@code protobuf.clientchannels.TextChannel}
   */
  public  static final class TextChannel extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.clientchannels.TextChannel)
      TextChannelOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TextChannel.newBuilder() to construct.
    private TextChannel(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TextChannel() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TextChannel();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TextChannel(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              protobuf.ClientChannels.ChannelBase.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) != 0)) {
                subBuilder = channelBase_.toBuilder();
              }
              channelBase_ = input.readMessage(protobuf.ClientChannels.ChannelBase.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(channelBase_);
                channelBase_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.ClientChannels.internal_static_protobuf_clientchannels_TextChannel_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.ClientChannels.internal_static_protobuf_clientchannels_TextChannel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.ClientChannels.TextChannel.class, protobuf.ClientChannels.TextChannel.Builder.class);
    }

    private int bitField0_;
    public static final int CHANNELBASE_FIELD_NUMBER = 1;
    private protobuf.ClientChannels.ChannelBase channelBase_;
    /**
     * <code>required .protobuf.clientchannels.ChannelBase channelBase = 1;</code>
     * @return Whether the channelBase field is set.
     */
    public boolean hasChannelBase() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .protobuf.clientchannels.ChannelBase channelBase = 1;</code>
     * @return The channelBase.
     */
    public protobuf.ClientChannels.ChannelBase getChannelBase() {
      return channelBase_ == null ? protobuf.ClientChannels.ChannelBase.getDefaultInstance() : channelBase_;
    }
    /**
     * <code>required .protobuf.clientchannels.ChannelBase channelBase = 1;</code>
     */
    public protobuf.ClientChannels.ChannelBaseOrBuilder getChannelBaseOrBuilder() {
      return channelBase_ == null ? protobuf.ClientChannels.ChannelBase.getDefaultInstance() : channelBase_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasChannelBase()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getChannelBase().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getChannelBase());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getChannelBase());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protobuf.ClientChannels.TextChannel)) {
        return super.equals(obj);
      }
      protobuf.ClientChannels.TextChannel other = (protobuf.ClientChannels.TextChannel) obj;

      if (hasChannelBase() != other.hasChannelBase()) return false;
      if (hasChannelBase()) {
        if (!getChannelBase()
            .equals(other.getChannelBase())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasChannelBase()) {
        hash = (37 * hash) + CHANNELBASE_FIELD_NUMBER;
        hash = (53 * hash) + getChannelBase().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobuf.ClientChannels.TextChannel parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.ClientChannels.TextChannel parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.ClientChannels.TextChannel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.ClientChannels.TextChannel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.ClientChannels.TextChannel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.ClientChannels.TextChannel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.ClientChannels.TextChannel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.ClientChannels.TextChannel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.ClientChannels.TextChannel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protobuf.ClientChannels.TextChannel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.ClientChannels.TextChannel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.ClientChannels.TextChannel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.ClientChannels.TextChannel prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.clientchannels.TextChannel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.clientchannels.TextChannel)
        protobuf.ClientChannels.TextChannelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.ClientChannels.internal_static_protobuf_clientchannels_TextChannel_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.ClientChannels.internal_static_protobuf_clientchannels_TextChannel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.ClientChannels.TextChannel.class, protobuf.ClientChannels.TextChannel.Builder.class);
      }

      // Construct using protobuf.ClientChannels.TextChannel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getChannelBaseFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (channelBaseBuilder_ == null) {
          channelBase_ = null;
        } else {
          channelBaseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.ClientChannels.internal_static_protobuf_clientchannels_TextChannel_descriptor;
      }

      @java.lang.Override
      public protobuf.ClientChannels.TextChannel getDefaultInstanceForType() {
        return protobuf.ClientChannels.TextChannel.getDefaultInstance();
      }

      @java.lang.Override
      public protobuf.ClientChannels.TextChannel build() {
        protobuf.ClientChannels.TextChannel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protobuf.ClientChannels.TextChannel buildPartial() {
        protobuf.ClientChannels.TextChannel result = new protobuf.ClientChannels.TextChannel(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          if (channelBaseBuilder_ == null) {
            result.channelBase_ = channelBase_;
          } else {
            result.channelBase_ = channelBaseBuilder_.build();
          }
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.ClientChannels.TextChannel) {
          return mergeFrom((protobuf.ClientChannels.TextChannel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.ClientChannels.TextChannel other) {
        if (other == protobuf.ClientChannels.TextChannel.getDefaultInstance()) return this;
        if (other.hasChannelBase()) {
          mergeChannelBase(other.getChannelBase());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasChannelBase()) {
          return false;
        }
        if (!getChannelBase().isInitialized()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.ClientChannels.TextChannel parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.ClientChannels.TextChannel) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private protobuf.ClientChannels.ChannelBase channelBase_;
      private com.google.protobuf.SingleFieldBuilderV3<
          protobuf.ClientChannels.ChannelBase, protobuf.ClientChannels.ChannelBase.Builder, protobuf.ClientChannels.ChannelBaseOrBuilder> channelBaseBuilder_;
      /**
       * <code>required .protobuf.clientchannels.ChannelBase channelBase = 1;</code>
       * @return Whether the channelBase field is set.
       */
      public boolean hasChannelBase() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required .protobuf.clientchannels.ChannelBase channelBase = 1;</code>
       * @return The channelBase.
       */
      public protobuf.ClientChannels.ChannelBase getChannelBase() {
        if (channelBaseBuilder_ == null) {
          return channelBase_ == null ? protobuf.ClientChannels.ChannelBase.getDefaultInstance() : channelBase_;
        } else {
          return channelBaseBuilder_.getMessage();
        }
      }
      /**
       * <code>required .protobuf.clientchannels.ChannelBase channelBase = 1;</code>
       */
      public Builder setChannelBase(protobuf.ClientChannels.ChannelBase value) {
        if (channelBaseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          channelBase_ = value;
          onChanged();
        } else {
          channelBaseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .protobuf.clientchannels.ChannelBase channelBase = 1;</code>
       */
      public Builder setChannelBase(
          protobuf.ClientChannels.ChannelBase.Builder builderForValue) {
        if (channelBaseBuilder_ == null) {
          channelBase_ = builderForValue.build();
          onChanged();
        } else {
          channelBaseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .protobuf.clientchannels.ChannelBase channelBase = 1;</code>
       */
      public Builder mergeChannelBase(protobuf.ClientChannels.ChannelBase value) {
        if (channelBaseBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
              channelBase_ != null &&
              channelBase_ != protobuf.ClientChannels.ChannelBase.getDefaultInstance()) {
            channelBase_ =
              protobuf.ClientChannels.ChannelBase.newBuilder(channelBase_).mergeFrom(value).buildPartial();
          } else {
            channelBase_ = value;
          }
          onChanged();
        } else {
          channelBaseBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .protobuf.clientchannels.ChannelBase channelBase = 1;</code>
       */
      public Builder clearChannelBase() {
        if (channelBaseBuilder_ == null) {
          channelBase_ = null;
          onChanged();
        } else {
          channelBaseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .protobuf.clientchannels.ChannelBase channelBase = 1;</code>
       */
      public protobuf.ClientChannels.ChannelBase.Builder getChannelBaseBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getChannelBaseFieldBuilder().getBuilder();
      }
      /**
       * <code>required .protobuf.clientchannels.ChannelBase channelBase = 1;</code>
       */
      public protobuf.ClientChannels.ChannelBaseOrBuilder getChannelBaseOrBuilder() {
        if (channelBaseBuilder_ != null) {
          return channelBaseBuilder_.getMessageOrBuilder();
        } else {
          return channelBase_ == null ?
              protobuf.ClientChannels.ChannelBase.getDefaultInstance() : channelBase_;
        }
      }
      /**
       * <code>required .protobuf.clientchannels.ChannelBase channelBase = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          protobuf.ClientChannels.ChannelBase, protobuf.ClientChannels.ChannelBase.Builder, protobuf.ClientChannels.ChannelBaseOrBuilder> 
          getChannelBaseFieldBuilder() {
        if (channelBaseBuilder_ == null) {
          channelBaseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              protobuf.ClientChannels.ChannelBase, protobuf.ClientChannels.ChannelBase.Builder, protobuf.ClientChannels.ChannelBaseOrBuilder>(
                  getChannelBase(),
                  getParentForChildren(),
                  isClean());
          channelBase_ = null;
        }
        return channelBaseBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.clientchannels.TextChannel)
    }

    // @@protoc_insertion_point(class_scope:protobuf.clientchannels.TextChannel)
    private static final protobuf.ClientChannels.TextChannel DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protobuf.ClientChannels.TextChannel();
    }

    public static protobuf.ClientChannels.TextChannel getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TextChannel>
        PARSER = new com.google.protobuf.AbstractParser<TextChannel>() {
      @java.lang.Override
      public TextChannel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TextChannel(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TextChannel> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TextChannel> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protobuf.ClientChannels.TextChannel getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface VoiceChannelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.clientchannels.VoiceChannel)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .protobuf.clientchannels.ChannelBase channelBase = 1;</code>
     * @return Whether the channelBase field is set.
     */
    boolean hasChannelBase();
    /**
     * <code>required .protobuf.clientchannels.ChannelBase channelBase = 1;</code>
     * @return The channelBase.
     */
    protobuf.ClientChannels.ChannelBase getChannelBase();
    /**
     * <code>required .protobuf.clientchannels.ChannelBase channelBase = 1;</code>
     */
    protobuf.ClientChannels.ChannelBaseOrBuilder getChannelBaseOrBuilder();
  }
  /**
   * Protobuf type {@code protobuf.clientchannels.VoiceChannel}
   */
  public  static final class VoiceChannel extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.clientchannels.VoiceChannel)
      VoiceChannelOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VoiceChannel.newBuilder() to construct.
    private VoiceChannel(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VoiceChannel() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new VoiceChannel();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private VoiceChannel(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              protobuf.ClientChannels.ChannelBase.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) != 0)) {
                subBuilder = channelBase_.toBuilder();
              }
              channelBase_ = input.readMessage(protobuf.ClientChannels.ChannelBase.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(channelBase_);
                channelBase_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.ClientChannels.internal_static_protobuf_clientchannels_VoiceChannel_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.ClientChannels.internal_static_protobuf_clientchannels_VoiceChannel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.ClientChannels.VoiceChannel.class, protobuf.ClientChannels.VoiceChannel.Builder.class);
    }

    private int bitField0_;
    public static final int CHANNELBASE_FIELD_NUMBER = 1;
    private protobuf.ClientChannels.ChannelBase channelBase_;
    /**
     * <code>required .protobuf.clientchannels.ChannelBase channelBase = 1;</code>
     * @return Whether the channelBase field is set.
     */
    public boolean hasChannelBase() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .protobuf.clientchannels.ChannelBase channelBase = 1;</code>
     * @return The channelBase.
     */
    public protobuf.ClientChannels.ChannelBase getChannelBase() {
      return channelBase_ == null ? protobuf.ClientChannels.ChannelBase.getDefaultInstance() : channelBase_;
    }
    /**
     * <code>required .protobuf.clientchannels.ChannelBase channelBase = 1;</code>
     */
    public protobuf.ClientChannels.ChannelBaseOrBuilder getChannelBaseOrBuilder() {
      return channelBase_ == null ? protobuf.ClientChannels.ChannelBase.getDefaultInstance() : channelBase_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasChannelBase()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getChannelBase().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getChannelBase());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getChannelBase());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protobuf.ClientChannels.VoiceChannel)) {
        return super.equals(obj);
      }
      protobuf.ClientChannels.VoiceChannel other = (protobuf.ClientChannels.VoiceChannel) obj;

      if (hasChannelBase() != other.hasChannelBase()) return false;
      if (hasChannelBase()) {
        if (!getChannelBase()
            .equals(other.getChannelBase())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasChannelBase()) {
        hash = (37 * hash) + CHANNELBASE_FIELD_NUMBER;
        hash = (53 * hash) + getChannelBase().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobuf.ClientChannels.VoiceChannel parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.ClientChannels.VoiceChannel parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.ClientChannels.VoiceChannel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.ClientChannels.VoiceChannel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.ClientChannels.VoiceChannel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.ClientChannels.VoiceChannel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.ClientChannels.VoiceChannel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.ClientChannels.VoiceChannel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.ClientChannels.VoiceChannel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protobuf.ClientChannels.VoiceChannel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.ClientChannels.VoiceChannel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.ClientChannels.VoiceChannel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.ClientChannels.VoiceChannel prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.clientchannels.VoiceChannel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.clientchannels.VoiceChannel)
        protobuf.ClientChannels.VoiceChannelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.ClientChannels.internal_static_protobuf_clientchannels_VoiceChannel_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.ClientChannels.internal_static_protobuf_clientchannels_VoiceChannel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.ClientChannels.VoiceChannel.class, protobuf.ClientChannels.VoiceChannel.Builder.class);
      }

      // Construct using protobuf.ClientChannels.VoiceChannel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getChannelBaseFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (channelBaseBuilder_ == null) {
          channelBase_ = null;
        } else {
          channelBaseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.ClientChannels.internal_static_protobuf_clientchannels_VoiceChannel_descriptor;
      }

      @java.lang.Override
      public protobuf.ClientChannels.VoiceChannel getDefaultInstanceForType() {
        return protobuf.ClientChannels.VoiceChannel.getDefaultInstance();
      }

      @java.lang.Override
      public protobuf.ClientChannels.VoiceChannel build() {
        protobuf.ClientChannels.VoiceChannel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protobuf.ClientChannels.VoiceChannel buildPartial() {
        protobuf.ClientChannels.VoiceChannel result = new protobuf.ClientChannels.VoiceChannel(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          if (channelBaseBuilder_ == null) {
            result.channelBase_ = channelBase_;
          } else {
            result.channelBase_ = channelBaseBuilder_.build();
          }
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.ClientChannels.VoiceChannel) {
          return mergeFrom((protobuf.ClientChannels.VoiceChannel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.ClientChannels.VoiceChannel other) {
        if (other == protobuf.ClientChannels.VoiceChannel.getDefaultInstance()) return this;
        if (other.hasChannelBase()) {
          mergeChannelBase(other.getChannelBase());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasChannelBase()) {
          return false;
        }
        if (!getChannelBase().isInitialized()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.ClientChannels.VoiceChannel parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.ClientChannels.VoiceChannel) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private protobuf.ClientChannels.ChannelBase channelBase_;
      private com.google.protobuf.SingleFieldBuilderV3<
          protobuf.ClientChannels.ChannelBase, protobuf.ClientChannels.ChannelBase.Builder, protobuf.ClientChannels.ChannelBaseOrBuilder> channelBaseBuilder_;
      /**
       * <code>required .protobuf.clientchannels.ChannelBase channelBase = 1;</code>
       * @return Whether the channelBase field is set.
       */
      public boolean hasChannelBase() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required .protobuf.clientchannels.ChannelBase channelBase = 1;</code>
       * @return The channelBase.
       */
      public protobuf.ClientChannels.ChannelBase getChannelBase() {
        if (channelBaseBuilder_ == null) {
          return channelBase_ == null ? protobuf.ClientChannels.ChannelBase.getDefaultInstance() : channelBase_;
        } else {
          return channelBaseBuilder_.getMessage();
        }
      }
      /**
       * <code>required .protobuf.clientchannels.ChannelBase channelBase = 1;</code>
       */
      public Builder setChannelBase(protobuf.ClientChannels.ChannelBase value) {
        if (channelBaseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          channelBase_ = value;
          onChanged();
        } else {
          channelBaseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .protobuf.clientchannels.ChannelBase channelBase = 1;</code>
       */
      public Builder setChannelBase(
          protobuf.ClientChannels.ChannelBase.Builder builderForValue) {
        if (channelBaseBuilder_ == null) {
          channelBase_ = builderForValue.build();
          onChanged();
        } else {
          channelBaseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .protobuf.clientchannels.ChannelBase channelBase = 1;</code>
       */
      public Builder mergeChannelBase(protobuf.ClientChannels.ChannelBase value) {
        if (channelBaseBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
              channelBase_ != null &&
              channelBase_ != protobuf.ClientChannels.ChannelBase.getDefaultInstance()) {
            channelBase_ =
              protobuf.ClientChannels.ChannelBase.newBuilder(channelBase_).mergeFrom(value).buildPartial();
          } else {
            channelBase_ = value;
          }
          onChanged();
        } else {
          channelBaseBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .protobuf.clientchannels.ChannelBase channelBase = 1;</code>
       */
      public Builder clearChannelBase() {
        if (channelBaseBuilder_ == null) {
          channelBase_ = null;
          onChanged();
        } else {
          channelBaseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .protobuf.clientchannels.ChannelBase channelBase = 1;</code>
       */
      public protobuf.ClientChannels.ChannelBase.Builder getChannelBaseBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getChannelBaseFieldBuilder().getBuilder();
      }
      /**
       * <code>required .protobuf.clientchannels.ChannelBase channelBase = 1;</code>
       */
      public protobuf.ClientChannels.ChannelBaseOrBuilder getChannelBaseOrBuilder() {
        if (channelBaseBuilder_ != null) {
          return channelBaseBuilder_.getMessageOrBuilder();
        } else {
          return channelBase_ == null ?
              protobuf.ClientChannels.ChannelBase.getDefaultInstance() : channelBase_;
        }
      }
      /**
       * <code>required .protobuf.clientchannels.ChannelBase channelBase = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          protobuf.ClientChannels.ChannelBase, protobuf.ClientChannels.ChannelBase.Builder, protobuf.ClientChannels.ChannelBaseOrBuilder> 
          getChannelBaseFieldBuilder() {
        if (channelBaseBuilder_ == null) {
          channelBaseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              protobuf.ClientChannels.ChannelBase, protobuf.ClientChannels.ChannelBase.Builder, protobuf.ClientChannels.ChannelBaseOrBuilder>(
                  getChannelBase(),
                  getParentForChildren(),
                  isClean());
          channelBase_ = null;
        }
        return channelBaseBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.clientchannels.VoiceChannel)
    }

    // @@protoc_insertion_point(class_scope:protobuf.clientchannels.VoiceChannel)
    private static final protobuf.ClientChannels.VoiceChannel DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protobuf.ClientChannels.VoiceChannel();
    }

    public static protobuf.ClientChannels.VoiceChannel getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<VoiceChannel>
        PARSER = new com.google.protobuf.AbstractParser<VoiceChannel>() {
      @java.lang.Override
      public VoiceChannel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VoiceChannel(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<VoiceChannel> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VoiceChannel> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protobuf.ClientChannels.VoiceChannel getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_clientchannels_ChannelBase_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_clientchannels_ChannelBase_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_clientchannels_TextChannel_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_clientchannels_TextChannel_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_clientchannels_VoiceChannel_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_clientchannels_VoiceChannel_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035protobuf/ClientChannels.proto\022\027protobu" +
      "f.clientchannels\"\374\001\n\013ChannelBase\022\021\n\tchan" +
      "nelId\030\001 \002(\005\022\023\n\013channelName\030\002 \002(\t\022\020\n\010memb" +
      "erId\030\003 \003(\005\022\022\n\nmaxMembers\030\004 \002(\005\022T\n\017restri" +
      "ctionType\030\005 \002(\0162;.protobuf.clientchannel" +
      "s.ChannelBase.ChannelRestrictionType\"I\n\026" +
      "ChannelRestrictionType\022\n\n\006PUBLIC\020\000\022\022\n\016WH" +
      "ITELIST_ONLY\020\001\022\017\n\013INVITE_ONLY\020\002\"H\n\013TextC" +
      "hannel\0229\n\013channelBase\030\001 \002(\0132$.protobuf.c" +
      "lientchannels.ChannelBase\"I\n\014VoiceChanne" +
      "l\0229\n\013channelBase\030\001 \002(\0132$.protobuf.client" +
      "channels.ChannelBaseB\032\n\010protobufB\016Client" +
      "Channels"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protobuf_clientchannels_ChannelBase_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_clientchannels_ChannelBase_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_clientchannels_ChannelBase_descriptor,
        new java.lang.String[] { "ChannelId", "ChannelName", "MemberId", "MaxMembers", "RestrictionType", });
    internal_static_protobuf_clientchannels_TextChannel_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protobuf_clientchannels_TextChannel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_clientchannels_TextChannel_descriptor,
        new java.lang.String[] { "ChannelBase", });
    internal_static_protobuf_clientchannels_VoiceChannel_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_protobuf_clientchannels_VoiceChannel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_clientchannels_VoiceChannel_descriptor,
        new java.lang.String[] { "ChannelBase", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
